apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: main_db:5432
    user: ${MAIN_DB_USERNAME}
    secureJsonData:
      password: ${MAIN_DB_PASSWORD}
    jsonData:
      database: ${MAIN_DB_DATABASE_NAME}
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false